language: node_js
node_js:
  - "14"

install:
  - npm install

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/cypress --version

script:
  - cypress run --record --key a11dc96e-dc53-439c-be79-fc7858f756b8